config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #read all the tasks

  get "/tasks", to: "tasks#index"

  #read a page from one specific task

  get "/task/new", to: "tasks#new", as: :new_task
  post "/tasks", to: "tasks#create"

  get "/task/:id", to: "tasks#show", as: :task

  #create


  #update

  get "/task/:id/edit", to: "tasks#edit", as: :edit_task
  patch "/task/:id", to: "tasks#update"

  #delete

  delete "/task/:id", to: "tasks#destroy", as: :destroy_task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
        if @task.completed == false
      @status = "Not completed"
    else
      @status = "completed"
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.title %></h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>All tasks</h1>

<% @tasks.each do |task| %>
<%= link_to task.title, task_path(task) %>

<% end %>

<%= link_to "Add a new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h1>


<h3><%= @task.details %></h2>


<p><%= @status %></p>

<%= link_to "Edit the task", edit_task_path(@task) %>
<%= link_to "Back to list", tasks_path %>
<%= link_to "Delete", destroy_task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>